//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorsAndPatients {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorsAndPatients.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\School\School\SD\SensorsAndPatients\SensorsAndPatients\Resource\activity.txt.
        /// </summary>
        internal static string activity {
            get {
                return ResourceManager.GetString("activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011-11-28 02:27:59		2011-11-28 10:18:11		Sleeping		
        ///2011-11-28 10:21:24		2011-11-28 10:23:36		Toileting	
        ///2011-11-28 10:25:44		2011-11-28 10:33:00		Showering	
        ///2011-11-28 10:34:23		2011-11-28 10:43:00		Breakfast	
        ///2011-11-28 10:49:48		2011-11-28 10:51:13		Grooming	
        ///2011-11-28 10:51:41		2011-11-28 13:05:07		Spare_Time/TV		
        ///2011-11-28 13:06:04		2011-11-28 13:06:31		Toileting	
        ///2011-11-28 13:09:31		2011-11-28 13:29:09		Leaving	
        ///2011-11-28 13:38:40		2011-11-28 14:21:40		Spare_Time/TV		
        ///2011-11-28 14:22:38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string activity1 {
            get {
                return ResourceManager.GetString("activity1", resourceCulture);
            }
        }
    }
}
