//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doc1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int patient_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime birthdate { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public int doctor { get; set; }
        public Nullable<int> caregiver { get; set; }
        public Nullable<int> medication_plan { get; set; }
    
        public virtual Caregiver Caregiver1 { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Medication_Plan Medication_Plan1 { get; set; }
    }
}
